name: Testing with pytest 

on:
  pull_request:
    branches: [ main, team1sprint2, team1sprint3, team1sprint4 ]
    types:
      - opened
      - edited
      - synchronize
  push:
    branches:
      - team2sprint6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f setup.py ]; then pip install .[development]; fi

      - name: Install pytest plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Test with pytest
        run: pytest
